Some error corrections and some enhancement done
iobroker-community-adapters/ioBroker.ring pull request #575
Opened 2023-09-05 15:47 UTC by crocri

- Ding event is now working again (ring Interkom)
- auto livestream creation takes now value from config, before fix
- snapshot now async, because snapshot and livestream in parallel does not work
- livestream duration now settable via tree entry
  will be auto reset via livestream request. After request is done, duration time is reset to config value
- two new config entries: auto_livestream and auto_snapshot - can be disabled now if someone wants to react manually
- some minor corrections to code

2023-09-05 18:43 UTC, mcm1957 reviewed
Please remove line
```"installedFrom": "iobroker-community-adapters/ioBroker.ring"```
from package.json.

Codechanges should be reviewed by @theimo1221

2023-09-05 18:47 UTC, theimo1221 requested changes
Files in `build/` directory are generated during `npm run build` so all of your changes in that folder would be overwritten during next changes.
So you have to perform your changes within `src/` folder in the respective TypeScript file.

2023-09-05 18:49 UTC, theimo1221 commented on build/lib/ownRingCamera.js
> +       if (this._autoSnapshot || this._autoLiveStream) {
Inverting this statement you would reduce nesting, which improves code readability.

2023-09-06 00:50 UTC, crocri commented
- Removed "installedFrom": "iobroker-community-adapters/ioBroker.ring" (Martin, you mean io-package.json, right?)
- adapted ts files (but I'm not really qualified to do this Thiemo ;-)
- if expression inverted, correct Thiemo? if (a || b) -> if (!(a && b)), or do you mean anything else? If, do it by your own, please.

2023-09-06 20:52 UTC, theimo1221 commented
@crocri Thanks for modification permission and your changes.

<img width="907" alt="image" src="https://github.com/iobroker-community-adapters/ioBroker.ring/assets/20605452/1460da4f-79c1-497d-a773-21a0cdcbc026">

Did you open/editted the code in an IDE like VsCode?
Additionaly running `npm run build` results in multiple compilation issues.

I'll see if I can fix those quickly

2023-09-07 00:18 UTC, crocri commented
Nope, heard the first time from VsCode (Microsoft). Never developed an iobroker adapter, only look into the build code directly. Changes done and tested in my ioBroker system only.

2023-09-07 06:24 UTC, theimo1221 commented
Good Morning @crocri,

could you test the newest version within your system?

In general IDEs (Webstorm would be the one I personally use) are programs which help you to write/edit/inspect/run code.
Like in this case, installing the npm packages, performing the build process, marking errors/mistakes, giving auto-completion, etc. So if you want to dig deeper into this space, I'd recommend trying e.g. VsCode as it is free.

2023-09-08 18:53 UTC, crocri commented
ioBroker dev (VM) and VS Code installed, "new" ring adapter compiled and tested. No issues left (after debugging ;-)

2023-09-16 08:42 UTC, theimo1221 commented
Thanks @crocri will review this later today

2023-09-16 09:33 UTC, theimo1221 commented
Later on a deep dive into your ownRingDevice changes is necessary and a functional test is pending, afterwards we could proceed.

2023-09-16 11:47 UTC, merged