Small bug and some code clean up
iobroker-community-adapters/ioBroker.ring pull request #606
Opened 2023-10-31 02:04 UTC by crocri

Hi!
- You have an error in new Eventblocker (ding/doorbell objects not used in function).
- Can we change Eventblocker and add constructor to it? Both config settings should not be changeable during runtime.
- ownRingCamera and ownRingIntercom "same" order of get, set and constructor - more readable (especially for me ;-)
- added Eventblocker also to ownRingInterkom (here ding event is also a doorbell)
- set time for unset doorbell to one second (ownRingCamera and ownRingIntercom) - it works also with100 ms w/o any problems

And your solution with Eventblocker as class is the better one (I'm just learning every day...)

Best regards
Crocri

2023-10-31 16:40 UTC, crocri commented
Hello!
Can someone explain, why this.subscribeToEvents() is not working, but this._ringIntercom = ringDevice works?
I have no idea. Nevertheless, I have changed this in ownRingIntercom and also in ownRingCamera (in ownRingCamera it is working with this.subscribeToEvents() - what is the difference?)

2023-11-01 07:20 UTC, theimo1221 commented
> Hello! Can someone explain, why this.subscribeToEvents() is not working, but this.ringIntercom = ringDevice works? I have no idea. Nevertheless, I have changed this in ownRingIntercom and also in ownRingCamera (in ownRingCamera it is working with this.subscribeToEvents() - what is the difference?)

Good morning @crocri ,

https://github.com/iobroker-community-adapters/ioBroker.ring/blob/16421726c5207f46b44d9d7b431194f227e094bf/src/lib/ownRingIntercom.ts#L48-L51

So this setter does include the subscribing.

Additionally the behaviour of asynchronous calls within synchron events like object construction can be dangerous. So as the async happens within the setter, the surronding this-Context is more clear, which could be the reason for a direct call to `subscribeToEvents` in the constructor not working.
An other workaround could be to trigger the subscription wihtin a timeout, to ensure the object being correctly setup before moving to that async func.

2023-11-01 07:20 UTC, theimo1221 requested changes

2023-11-01 07:20 UTC, theimo1221 commented on src/lib/ownRingCamera.ts
> +    "motion":   new EventBlocker(this._adapter.config.ignore_events_Motion,   this._adapter.config.keep_ignoring_if_retriggered),
Please move initialization to constructor, as this._adapter is not definetly present at this point.

2023-11-01 07:20 UTC, theimo1221 commented on src/lib/ownRingCamera.ts
> +    this._ringDevice = ringDevice;
Unecessary due to the next line (which writes `this._ringDevice` anyways

2023-11-01 07:20 UTC, theimo1221 commented on src/lib/ownRingCamera.ts
> +    }, 1000);
Someone requested the state to be on true for a longer time, and as some doorbell ringtones play like 10-20s as well I'd personally be fine with keeping this at 5s

2023-11-01 07:20 UTC, theimo1221 commented on src/lib/ownRingIntercom.ts
> +    "ding": new EventBlocker(this._adapter.config.ignore_events_Doorbell, this._adapter.config.keep_ignoring_if_retriggered)
as this class has only one possible eventblocker, we shouldn't use a dictionary here.

A simple `private _evenBlocker: Eventblocker = ...` would be perfectly suffecient

2023-11-01 09:43 UTC, crocri commented on src/lib/ownRingCamera.ts
> +    "motion":   new EventBlocker(this._adapter.config.ignore_events_Motion,   this._adapter.config.keep_ignoring_if_retriggered),
Hi!
What do you mean? _adapter is defined, also config values. Just added adapter.log.debug(`Duration=${blockDuration}, Extend=${extendIfActive}` ); to constructor - values shown are correct (also added:  import { RingAdapter } from "../../main"). If never selected from user, it's pre-defined in io-package.json...

2023-11-01 09:46 UTC, crocri commented on src/lib/ownRingCamera.ts
> +    this._ringDevice = ringDevice;
I thought the same - but in ownRingIntercom is the same code:
this._ringIntercom = ringDevice;  // but NO subscription done
this.ringIntercom = ringDevice;   // now subscription is done

2023-11-01 09:56 UTC, crocri commented on src/lib/ownRingCamera.ts
> +    }, 1000);
Hm - the event is "s.o. pressed the doorbell", not "how long rings the bell", isn't it? If someone press again the doorbell, it tooks less than a second, not five seconds. We have also a melody, but if the bell is pressed again, melody is interrupted and starts from beginning.  If someone wants to react on the end of the own bell, this should be programmed individually, because this is always different from bell to bell and never exact 5 seconds. 
To react on the event, 100 ms are enough (tested many times). In which case I need 5 seconds and event set to false??

2023-11-01 10:04 UTC, crocri commented on src/lib/ownRingIntercom.ts
> +    "ding": new EventBlocker(this._adapter.config.ignore_events_Doorbell, this._adapter.config.keep_ignoring_if_retriggered)
Hi!
My intention was to make ownRingCamera and ownRingIntercom comparable. Do to the same things here (if possible) makes the code more comparable. It's a one time action as startup, so no timing issue.

2023-11-01 13:21 UTC, crocri commented
Hi!
Now I have it :-)
this._ringIntercom = ringDevice;   // calls no setter, but initialized variable for typescript
this.ringIntercom = ringDevice     // calls setter and inialize _ringIntercom too

private _ringIntercom: RingIntercom   // typescript do not recognize setter initialization by design, so use
private _ringIntercom!: RingIntercom  // be sure that variable is initialized afterwards!

With those changes, "this.ringIntercom = ringDevice" is sufficient, also for working subscription

Changed both, ownRingCamera and ownRingIntercom and cleand up not needed getter and setter.
Tests are fine, subscription is done now for camera and intercom.

In function "updateByDevice", why we need "this._ringIntercom  = intercom". Is it possible, that device changed on the fly?
If changed, we need also new subscription, right?

Best regards
Crocri

2023-11-01 22:30 UTC, theimo1221 commented
> Hi! Now I have it :-) this._ringIntercom = ringDevice; // calls no setter, but initialized variable for typescript this.ringIntercom = ringDevice // calls setter and inialize _ringIntercom too
> 
> private _ringIntercom: RingIntercom // typescript do not recognize setter initialization by design, so use private _ringIntercom!: RingIntercom // be sure that variable is initialized afterwards!

Whilst you are correct for the reason of both lines usage of the non-null assertion is an antipattern (for reference https://rules.sonarsource.com/typescript/RSPEC-2966/ ) and can lead to bugs if someone stumbles upon it.
So we should rather initialize the private and put the subscribing maybe in a timeout.

> In function "updateByDevice", why we need "this._ringIntercom = intercom". Is it possible, that device changed on the fly? If changed, we need also new subscription, right?
> 
> Best regards Crocri

As visible here we refresh all cameras from time to time:
https://github.com/iobroker-community-adapters/ioBroker.ring/blob/16421726c5207f46b44d9d7b431194f227e094bf/src/lib/ringApiClient.ts#L94-L138

So yes, we have to subscribe again, which is performed here, by calling the setter:
https://github.com/iobroker-community-adapters/ioBroker.ring/blob/16421726c5207f46b44d9d7b431194f227e094bf/src/lib/ownRingCamera.ts#L711-L715

2023-11-02 19:40 UTC, crocri commented
Hello!
After removing setter, subscription is working for both devices. All getter and setter removed, because there is no need for it. Now initialization is typescript like w/o this exclamation mark.

Best regards
Crocri

2023-11-03 17:29 UTC, theimo1221 commented
Hello @crocri,

thanks for your changes, but my point still stands.
In following scenario the new code will fail:
1. After 60 minutes of running, adapter will start refresh process
2. RingCameras and RingIntercom objects are changed
3. The devices don't resubscribe --> User won't get any further events

So whilst you removed the now faulty comment the reason for the comment still stands....

2023-11-04 14:35 UTC, crocri commented
Hi!
I have tested for one hour, but refresh process is two hours (120 * 60 * 1000). After removing setter, we have to add subscription to update function. Just tested and it works. After 2 hours a re-subscription is done for camera and intercom, and both events active again :-)
Now the code is clean and working, hopefully you agree.
Something with setter in parallel to initalize has not worked as expected before...

2023-11-05 12:56 UTC, merged